#!/usr/bin/env bash
# ============================================================================
# skills/nmap/sub-processes/sysreport.sh
#
# Phase 5: Generate human-readable YAML and structured JSON reports from
# the consolidated scan results.
#
# Reads: consolidated.json from the analyzer phase.
# Writes: reports/{target}/nmap/{scan_id}/sysreport.yaml
#         reports/{target}/nmap/{scan_id}/sysreport.json
# ============================================================================

set -euo pipefail

log_info()  { echo "[sysreport] [INFO]  $*"; }
log_warn()  { echo "[sysreport] [WARN]  $*" >&2; }
log_error() { echo "[sysreport] [ERROR] $*" >&2; }

TARGET="${TARGET:-}"
SCAN_ID="${SCAN_ID:-}"
STATE_DIR="${STATE_DIR:-state}"
REPORTS_DIR="${REPORTS_DIR:-reports}"
SKILL="${SKILL:-nmap}"

if [ -z "$TARGET" ] || [ -z "$SCAN_ID" ]; then
  log_error "TARGET and SCAN_ID must be set"
  exit 1
fi

OUTPUT_DIR="${STATE_DIR}/${SKILL}/${SCAN_ID}"
REPORT_DIR="${REPORTS_DIR}/${TARGET}/${SKILL}/${SCAN_ID}"
mkdir -p "$REPORT_DIR"

CONSOLIDATED="${OUTPUT_DIR}/consolidated.json"

# ---- Validate consolidated.json exists ----------------------------------
if [ ! -f "$CONSOLIDATED" ]; then
  log_error "consolidated.json not found at ${CONSOLIDATED}"
  log_info "Writing placeholder report indicating missing data"

  cat > "${REPORT_DIR}/sysreport.yaml" <<-YAMLEOF
# sysreport.yaml — Nmap Scan Report
# WARNING: consolidated.json was not available at report generation time.

scan_id: ${SCAN_ID}
target: ${TARGET}
status: incomplete
error: "consolidated.json not found — analysis phase may have failed"
generated_at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
YAMLEOF

  cat > "${REPORT_DIR}/sysreport.json" <<-JSONEOF
{
  "scan_id": "${SCAN_ID}",
  "target": "${TARGET}",
  "status": "incomplete",
  "error": "consolidated.json not found",
  "generated_at": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
}
JSONEOF

  exit 1
fi

# ---- Parse consolidated.json with jq ------------------------------------
log_info "Reading consolidated.json from ${CONSOLIDATED}"

# Validate JSON
if ! jq '.' "$CONSOLIDATED" > /dev/null 2>&1; then
  log_error "consolidated.json is invalid JSON"
  exit 1
fi

# Extract key fields
HOST_STATUS="$(jq -r '.host_status // "unknown"' "$CONSOLIDATED")"
PORT_COUNT="$(jq -r '.port_count // 0' "$CONSOLIDATED")"
OS_INFO="$(jq -r '.os_detection.os // "not detected"' "$CONSOLIDATED")"
OS_ACCURACY="$(jq -r '.os_detection.accuracy // "N/A"' "$CONSOLIDATED")"
RAW_XML="$(jq -r '.raw_xml // ""' "$CONSOLIDATED")"

# ---- Build port table for YAML ------------------------------------------
PORTS_YAML=""
if [ "$PORT_COUNT" -gt 0 ]; then
  PORTS_YAML="$(jq -r '.open_ports[] | [.port, .protocol, .service, .version] | @tsv' "$CONSOLIDATED" 2>/dev/null | \
    while IFS=$'\t' read -r port protocol service version; do
      echo "    - port: ${port}"
      echo "      protocol: ${protocol}"
      echo "      service: ${service:-unknown}"
      echo "      version: ${version:-""}"
    done || true)"
fi

# ---- Build NSE findings for YAML ----------------------------------------
NSE_YAML=""
NSE_COUNT="$(jq '.nse_findings | length' "$CONSOLIDATED" 2>/dev/null || echo 0)"
if [ "$NSE_COUNT" -gt 0 ]; then
  NSE_YAML="$(jq -r '.nse_findings[] | [.script, .output] | @tsv' "$CONSOLIDATED" 2>/dev/null | \
    while IFS=$'\t' read -r script output; do
      echo "  - script: ${script}"
      echo "    output: \"${output}\""
    done || true)"
fi

# ---- Build next_vectors for YAML ----------------------------------------
NEXT_YAML=""
NV_COUNT="$(jq '.next_vectors | length' "$CONSOLIDATED" 2>/dev/null || echo 0)"
if [ "$NV_COUNT" -gt 0 ]; then
  NEXT_YAML="$(jq -r '.next_vectors[] | [.skill, .weight, .reason] | @tsv' "$CONSOLIDATED" 2>/dev/null | \
    while IFS=$'\t' read -r skill weight reason; do
      echo "  - skill: ${skill}"
      echo "    weight: ${weight}"
      echo "    reason: \"${reason}\""
    done || true)"
fi

# ---- Build fingerprints for YAML ----------------------------------------
FP_YAML=""
FP_COUNT="$(jq '.fingerprints | length' "$CONSOLIDATED" 2>/dev/null || echo 0)"
if [ "$FP_COUNT" -gt 0 ]; then
  FP_YAML="$(jq -r '.fingerprints[] | [.port, .fingerprint] | @tsv' "$CONSOLIDATED" 2>/dev/null | \
    while IFS=$'\t' read -r port fp; do
      echo "  - port: ${port}"
      echo "    fingerprint: \"${fp}\""
    done || true)"
fi

# ---- Generate YAML report -----------------------------------------------
YAML_FILE="${REPORT_DIR}/sysreport.yaml"
cat > "$YAML_FILE" <<-YAMLEOF
# sysreport.yaml — Nmap Scan Report
# Generated by skills/nmap/sub-processes/sysreport.sh

scan_id: ${SCAN_ID}
target: ${TARGET}
generated_at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
status: complete

## Summary

host_status: ${HOST_STATUS}
open_port_count: ${PORT_COUNT}
os_detection: ${OS_INFO}
os_accuracy: ${OS_ACCURACY}
raw_xml: ${RAW_XML}

## Open Ports

${PORTS_YAML:-  (none discovered)}

## NSE Findings

${NSE_YAML:-  (none)}

## Service Fingerprints

${FP_YAML:-  (none)}

## Next Vectors

${NEXT_YAML:-  (none — target is down or no services detected)}

## Raw Data

raw_xml: ${RAW_XML}
consolidated_json: ${CONSOLIDATED}
YAMLEOF

log_info "Wrote YAML report to ${YAML_FILE}"

# ---- Generate JSON report -----------------------------------------------
JSON_FILE="${REPORT_DIR}/sysreport.json"
# Copy consolidated and add report metadata
jq --arg ts "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
   '. + {"report_generated_at": $ts, "report_type": "nmap-sysreport"}' \
   "$CONSOLIDATED" > "$JSON_FILE" 2>/dev/null || {
  log_warn "jq merge failed, writing direct copy"
  cat "$CONSOLIDATED" > "$JSON_FILE"
}

log_info "Wrote JSON report to ${JSON_FILE}"
log_info "Report generation complete — ${PORT_COUNT} ports documented"
exit 0
