#!/usr/bin/env bash
# ============================================================================
# skills/dnsenum-sysreport/main.sh — DNS Sysreport Sub-Skill
#
# Generates YAML and JSON reports from the dnsenum-analyzer consolidated.json.
# Writes to reports/{target}/dnsenum/{YYYY-MM-DD/HH-MM-SS}/sysreport.yaml
# and sysreport.json.
#
# Invocation (engine contract — env vars):
#   SCAN_ID=abc TARGET=example.com \
#     bash skills/dnsenum-sysreport/main.sh
#
# State written:
#   state/dnsenum-sysreport/{scan_id}/status.json
#   state/dnsenum-sysreport/{scan_id}/sub-processes/sysreport.json
#
# Reports:
#   reports/{target}/dnsenum/{YYYY-MM-DD/HH-MM-SS}/sysreport.yaml
#   reports/{target}/dnsenum/{YYYY-MM-DD/HH-MM-SS}/sysreport.json
# ============================================================================

set -euo pipefail

SKILL_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "${SKILL_DIR}/../.." && pwd)"
STATE_DIR="${STATE_DIR:-${PROJECT_ROOT}/state}"
REPORTS_DIR="${REPORTS_DIR:-${PROJECT_ROOT}/reports}"

SKILL="dnsenum-sysreport"
STEP_ID="${STEP_ID:-dnsenum-sysreport}"

source "${PROJECT_ROOT}/skills/_shared/envelope.sh"

if [ $# -ge 1 ] && [ -f "$1" ]; then
  EVENT_FILE="$1"
  log_info "Reading event from: ${EVENT_FILE}"
  SCAN_ID="$(jq -r '.scan_id // empty' "$EVENT_FILE")"
  TARGET="$(jq -r '.target // empty' "$EVENT_FILE")"
else
  SCAN_ID="${SCAN_ID:-}"
  TARGET="${TARGET:-}"
fi

if [ -z "${SCAN_ID}" ] || [ -z "${TARGET}" ]; then
  log_error "Missing required inputs: SCAN_ID and TARGET"
  exit 1
fi

export SCAN_ID TARGET
PARTIAL="${PARTIAL:-false}"; export PARTIAL
STARTED_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"; export STARTED_AT

REPORT_TARGET="${TARGET#https://}"
REPORT_TARGET="${REPORT_TARGET#http://}"

OUTPUT_DIR="${STATE_DIR}/${SKILL}/${SCAN_ID}"
mkdir -p "${OUTPUT_DIR}/sub-processes"

REPORT_TS="$(report_timestamp)"
REPORT_BASE_DIR="${REPORTS_DIR}/${REPORT_TARGET}/dnsenum/${REPORT_TS}"
mkdir -p "$REPORT_BASE_DIR"
ln -sfn "${REPORT_BASE_DIR}" "${REPORTS_DIR}/${REPORT_TARGET}/dnsenum/latest" 2>/dev/null || true

# ---- Read predecessor output --------------------------------------------
CONSOLIDATED="$(read_predecessor_output "dnsenum-analyzer" "consolidated.json" || true)"
if [ -z "${CONSOLIDATED}" ] || [ ! -f "${CONSOLIDATED}" ]; then
  CANDIDATE="${STATE_DIR}/dnsenum-analyzer/${SCAN_ID}/consolidated.json"
  [ -f "${CANDIDATE}" ] && CONSOLIDATED="${CANDIDATE}"
fi

log_info "Starting DNS sysreport | scan_id=${SCAN_ID} target=${TARGET}"
write_status "sysreport" "running" 0 "${SCAN_ID}" "${TARGET}"

YAML_FILE="${REPORT_BASE_DIR}/sysreport.yaml"
JSON_FILE="${REPORT_BASE_DIR}/sysreport.json"
GENERATED_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

if [ -z "${CONSOLIDATED}" ] || [ ! -f "${CONSOLIDATED}" ]; then
  log_warn "consolidated.json not available — placeholder report"

  cat > "${YAML_FILE}" << YAML
# sysreport.yaml — DNS Enumeration Report
scan_id: ${SCAN_ID}
target: ${TARGET}
status: incomplete
error: "consolidated.json not found"
generated_at: ${GENERATED_AT}
YAML

  jq -n \
    --arg scan_id "${SCAN_ID}" \
    --arg target "${TARGET}" \
    --arg generated_at "${GENERATED_AT}" \
    '{scan_id: $scan_id, target: $target, status: "incomplete", error: "consolidated.json not found", generated_at: $generated_at}' \
    > "${JSON_FILE}"

  write_to_shared_dir "${SKILL}" "${YAML_FILE}"
  write_to_shared_dir "${SKILL}" "${JSON_FILE}"
  write_sub_process_result "sysreport" 0 "/dev/null" "/dev/null" 0 "${YAML_FILE}"
  write_status "sysreport" "degraded" 100 "${SCAN_ID}" "${TARGET}"
  exit 0
fi

# ---- Generate YAML -------------------------------------------------------
{
  printf '# sysreport.yaml — DNS Enumeration Report\n'
  printf '# Generated by skills/dnsenum-sysreport/main.sh\n'
  printf '# Target: %s\n' "${TARGET}"
  printf '# Scan ID: %s\n' "${SCAN_ID}"
  printf '# Generated: %s\n\n' "${GENERATED_AT}"

  jq -r '
    "scan_id: \(.scan_id)\ntarget: \(.target)\ndomain: \(.domain)\nstarted_at: \(.started_at)\nseverity: \(.severity)\nsubdomain_count: \(.subdomain_count)\npartial: \(.partial)\n\n" +
    "zone_transfer:\n  attempted: \(.zone_transfer.attempted)\n  success: \(.zone_transfer.success)\n  record_count: \(.zone_transfer.records | length)\n\n" +
    "subdomains:\n" + (
      if (.subdomains | length) > 0 then
        (.subdomains | map(
          "  - name: \(.name)\n    ip: \(.ip | if . == "" then "-" else . end)\n    source: \(.source)"
        ) | join("\n"))
      else
        "  (none)"
      end
    ) + "\n\nnameservers:\n" + (
      if (.ns | length) > 0 then (.ns | map("  - \(.)") | join("\n")) else "  (none)" end
    ) + "\n\nmail_exchange:\n" + (
      if (.mx | length) > 0 then (.mx | map("  - \(.)") | join("\n")) else "  (none)" end
    ) + "\n\nnext_vectors:\n" + (
      if (.next_vectors | length) > 0 then
        (.next_vectors | map(
          "  - condition: \(.condition)\n    skill: \(.skill)\n    weight: \(.weight)\n    targets: \(.targets | if . == null then 0 else length end)\n    reason: \(.reason)"
        ) | join("\n"))
      else
        "  (none)"
      end
    )
  ' "${CONSOLIDATED}" 2>/dev/null >> "${YAML_FILE}" || {
    printf "scan_id: %s\ntarget: %s\nstatus: degraded\nerror: YAML generation failed\n" \
      "${SCAN_ID}" "${TARGET}" >> "${YAML_FILE}"
  }
} >/dev/null 2>&1

# ---- Generate JSON -------------------------------------------------------
jq '{
  scan_id: .scan_id,
  target: .target,
  domain: .domain,
  started_at: .started_at,
  generated_at: $ts,
  report_type: "dnsenum-sysreport",
  severity: .severity,
  subdomain_count: .subdomain_count,
  subdomains: .subdomains,
  ns: .ns,
  mx: .mx,
  zone_transfer: {
    attempted: .zone_transfer.attempted,
    success: .zone_transfer.success,
    record_count: (.zone_transfer.records | length)
  },
  next_vectors: .next_vectors,
  partial: .partial
}' --arg ts "${GENERATED_AT}" "${CONSOLIDATED}" 2>/dev/null > "${JSON_FILE}" || {
  jq -n \
    --arg scan_id "${SCAN_ID}" \
    --arg target "${TARGET}" \
    --arg generated_at "${GENERATED_AT}" \
    '{scan_id: $scan_id, target: $target, status: "degraded", error: "JSON generation failed", generated_at: $generated_at}' \
    > "${JSON_FILE}"
}

write_sub_process_result "sysreport" 0 "/dev/null" "/dev/null" 0 "${YAML_FILE}"
write_to_shared_dir "${SKILL}" "${YAML_FILE}"
write_to_shared_dir "${SKILL}" "${JSON_FILE}"
write_status "sysreport" "done" 100 "${SCAN_ID}" "${TARGET}"
log_info "dnsenum-sysreport finished | scan_id=${SCAN_ID} files=${YAML_FILE} ${JSON_FILE}"
